### PR TITLE
Fix issue #32 - TypeScript support

### PR DESCRIPTION
**Pull request by dobromyslov**
https://github.com/sendpulse/sendpulse-rest-api-node.js/issues/32
Added definitions for TypeScript with dts-gen util.

### CODE REVIEW

**Comment by Ksmike** [comment]
THANKS!

**Comment by Ksmike** [comment]
Can you merge this?

**Comment by dobromyslov** [comment]
@Ksmike no, I have no permissions. 

I created a ticket in the SendPulse service desk long time ago. They said that will check this PR. But no results...
Looks like they have no interest in this API.

I use my own build from the forked repo.

**Comment by Ksmike** [comment]
@dobromyslov Thanks for the work! I'll email them and ping their customer support as well see if we can motivate them!

**Comment by Ksmike** [comment]
Thansk guys!

**Pull request merged**
